### PR TITLE
Feature/model integration

### PR DESCRIPTION
**Pull request by romaninsh**
Schema migration class should be friendly with Agile Data. This PR adds the following features:

 - $migration->fromModel($m) - read table schema from a model
 - $migration->fromTable($table) - read table schema from SQL table
 - $migration->exportModel() - create quick'n'dirty model object for current migration
 - $migration->migrate() - compare current migration with actual data and alter
 - composer now recommend atk4/data

How to use:

``` php
$m = new Migration(new User($db));
$m->migrate(); // make sure table for User exists and has correct fields.

// or

$m = new Migration($db);
$m->fromTable('stats');
$app->add('CRUD')->setModel($m->exportModel());
```

### CODE REVIEW

**Comment by romaninsh** [comment]
Adding BC-Break, because "Migration" can no longer be used. Developer should replace it with either Migration\MySQL or Migration\SQLite.

**Comment by romaninsh** [comment]
Migration now works as before, but using sub-class is advised.

**Comment by dvc** [comment]
Production development requires not only schema create/update, but also:
- migrations version history
- bulk update/rollback any number of increment migrations
- auto generate many-to-many intermediate tables, indexes and foreign keys is very cool feature too

We need tool to (semi)auto support DDL evolution process, not only SQL mapping.  Like doctrine-migrations.

I`m not clear understand how to do this in your pattern? Do you have enough metadata for this?

**Comment by romaninsh** [comment]
@dvc, clearly no. I do not think this project can substitute "doctrine-migrations". Perhaps over time it will be comparable.

For now this implementation allows to extract structure as defined in model's persistence-specific configuration and apply it to SQL databases. The goal for now is to wrap "migrations" into a friendly Wizard (https://github.com/atk4/ui/pull/305).

Regarding histories - there is nothing of this sort, i suppose we can store migrations in files than track which migrations have been applied and which not, but that's some idea for the future. Other ideas can also be added as a ticket. We can discuss how to implement them, but I'd probably need to investigate alternative products first.

**Pull request merged**
